name:                hcheckers
version:             0.1.0.0
github:              "githubuser/hcheckers"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hcheckers#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- unordered-containers
- hashtables
- concurrent-extra
- stm-containers
- psqueues
- aeson
- yaml
- stm
- exceptions
- bytestring
- text
- hashable
- bytes
- bits
- scotty
- http-types
- clock
- array
- random
- binary
- store
- filepath
- directory
- unix
- unix-bytestring
- data-default
- megaparsec
- fast-logger
- heavy-logger
- text-format-heavy
- ekg
- ekg-core
- monad-metrics
- microlens
- random-access-file
- mwc-random
- template-haskell
- hsyslog
- optparse-applicative

flags:
  verbose:
    description: enable verbose logging of move search
    manual: false
    default: false

executables:
  hcheckersd:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -fwarn-unused-imports
    when:
      - condition: flag(verbose)
        cpp-options: -DVERBOSE
    dependencies: []

